import 'dayjs/locale/en';
import type {FluentTemplate} from './type';

const en_US: FluentTemplate = {
  home: 'Home',
  categories: 'Categories',
  collections: 'Collections',
  profile: 'Profile',

  'top-selling': 'Top Selling',
  'see-all': 'See All',
  'latest-products': 'Latest Products',
  'trending-products': 'Trending Products',
  'sign-in': 'Sign In',
  'sign-in-to-view-your-profile': 'Sign in to view your profile and orders',
  'signing-in': 'Signing in...',
  email: 'Email',
  'enter-your-email': 'Enter your email',
  password: 'Password',
  'enter-your-password': 'Enter your password',
  'dont-have-an-account': "Don't have an account? Register",
  'invalid-credentials': 'Invalid credentials. Please try again.',
  'no-collections-found': 'No collections found',
  cart: 'Cart',
  checkout: 'Checkout',
  'go-home': 'Go Home',
  'you-dont-have-anything-in-your-cart':
    "You don't have anything in your cart.\nUse the link below to start below to start browsing our products.",
  'profile-information': 'Profile Information',
  'order-with-id': 'Order # { $id }',
  orders: 'Orders',
  'shipping-addresses': 'Shipping Addresses',
  logout: 'Logout',
  'profile-details': 'Profile Details',
  name: 'Name',
  phone: 'Phone',
  'edit-profile': 'Edit Profile',
  save: 'Save',
  cancel: 'Cancel',
  'first-name': 'First Name',
  'last-name': 'Last Name',
  'no-orders-found': 'No orders found',
  'sign-in-to-view-orders': 'Please sign in to view your orders',
  view: 'View',
  'remaining-items': '{ $count } more',
  'no-categories-found': 'No categories found',
  variant: 'Variant',
  'add-a-promo-code': 'Add a Promo Code',
  'enter-promo-code': 'Enter promo code',
  'applied-promotions': 'Applied Promotions',
  'invalid-promo-code': 'Invalid promo code',
  'failed-to-apply-promotion': 'Failed to apply promotion code',
  'failed-to-remove-promotion': 'Failed to remove promotion code',
  apply: 'Apply',
  summary: 'Summary',
  discount: 'Discount',
  subtotal: 'Subtotal',
  shipping: 'Shipping',
  taxes: 'Taxes',
  total: 'Total',
  'use-same-address-for-billing': 'Use same address for billing',
  'shipping-address': 'Shipping Address',
  'billing-address': 'Billing Address',
  address: 'Address',
  company: 'Company',
  optional: 'Optional',
  'postal-code': 'Postal Code',
  city: 'City',
  'province-or-state': 'Province/State',
  country: 'Country',
  'select-a-country': 'Select a country',
  delivery: 'Delivery',
  payment: 'Payment',
  review: 'Review',
  'continue-to-delivery': 'Continue to Delivery',
  'continue-to-payment': 'Continue to Payment',
  'review-order': 'Review Order',
  'pay-using-provider': 'Pay using { $provider }',
  'place-order': 'Place Order',
  continue: 'Continue',
  'please-select-a-payment-method': 'Please select a payment provider',
  'no-cart-found': 'No cart found',
  'payment-provider-not-supported': 'Payment provider not supported',
  'failed-to-complete-order': 'Failed to complete order',
  error: 'Error',
  'an-error-occurred': 'An error occurred',
  'no-cart-id': 'No cart ID',
  'failed-to-update-shipping-method': 'Failed to update shipping method',
  'loading-shipping-options': 'Loading shipping options',
  'select-shipping-method': 'Select Shipping Method',
  calculating: 'Calculating',
  'no-region-id': 'No region ID',
  'stripe-payment-coming-soon': 'Stripe payment UI coming soon!',
  'no-additional-actions-required-for-manual-payment':
    'No additional actions required for manual payment.',
  'payment-provider-is-in-development':
    'Payment provider { $provider } is in development.',
  'loading-payment-options': 'Loading payment options',
  'select-payment-method': 'Select Payment Method',
  qty: 'Qty',
  'shipping-method': 'Shipping Method',
  'payment-method': 'Payment Method',
  'no-shipping-method-selected': 'No shipping method selected',
  'no-payment-method-selected': 'No payment method selected',
  canceled: 'Canceled',
  'not-fulfilled': 'Not Fulfilled',
  'partially-fulfilled': 'Partially Fulfilled',
  fulfilled: 'Fulfilled',
  'partially-shipped': 'Partially Shipped',
  shipped: 'Shipped',
  'partially-delivered': 'Partially Delivered',
  delivered: 'Delivered',
  'count-items': '{ $count } item(s)',
  'order-details': 'Order Details',
  'order-not-found': 'Order not found',
  'placed-on': 'Placed { $datetime }',
  status: 'Status',
  'order-items': 'Order Items',
  contact: 'Contact',
  method: 'Method',
  'order-summary': 'Order Summary',
  'continue-shopping': 'Continue Shopping',
  addresses: 'Addresses',
  'please-sign-in-to-view-your-address':
    'Please sign in to view your addresses',
  'no-addresses-found': 'No addresses found',
  'add-new-address': 'Add New Address',
  'add-address': 'Add Address',
  'edit-address': 'Edit Address',
  'save-changes': 'Save Changes',
  'country-code': 'Country Code',
  'product-information': 'Product Information',
  material: 'Material',
  'country-of-origin': 'Country of origin',
  type: 'Type',
  weight: 'Weight',
  dimensions: 'Dimensions',
  'days-return': '{ $count } day(s) return',
  'fast-delivery': 'Fast Delivery',
  'add-to-cart': 'Add to cart',
  'out-of-stock': 'Out of stock',
  'view-cart': 'View cart',
  settings: 'Settings',
  language: 'Language',
  'select-language': 'Select language',
  'language-is-required': 'Language is required',
  'first-name-is-required': 'First name is required',
  'last-name-is-required': 'Last name is required',
  'address-is-required': 'Address is required',
  'postal-code-is-required': 'Postal code is required',
  'city-is-required': 'City is required',
  'country-is-required': 'Country is required',
  'phone-is-required': 'Phone is required',
  'please-enter-a-valid-email': 'Please enter a valid email',
  'invalid-email-address': 'Invalid email address',
  'password-must-be-at-least-n-characters':
    'Password must be at least { $n } characters',
  register: 'Register',
  'enter-your-first-name': 'Enter your first name',
  'enter-your-last-name': 'Enter your last name',
  'create-account': 'Create Account',
  'creating-account': 'Creating account',
  'already-have-an-account': 'Already have an account? Sign In',
  'registration-failed': 'Registration failed. Please try again.',
};

export default Object.keys(en_US)
  .map(key => `${key} = ${(en_US as any)[key]}`)
  .join('\n');
